# Generated by Django 5.2.8 on 2025-11-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_default_password',
            field=models.BooleanField(default=True),
        ),
    ]
